### PR TITLE
Bug fixes to make CHIME grids work

### PR DESCRIPTION
**Pull request by profxj**
As titled.

Also added a Notebook and a test

### CODE REVIEW

**Review by cwjames1983 — COMMENTED** [review]
I've checked everything except the ipython, about which I know nothing.

@JordanHoffmann3 can you check this one?

**Comment by JordanHoffmann3** [comment]
Yep, the notebook looks fine

**Comment by JordanHoffmann3** [comment]
Yep the notebook looks fine

**Comment by JordanHoffmann3** [comment]
Woops accidentally closed this, but yet the notebook looks fine!!

**Review by JordanHoffmann3 — APPROVED** [review]
Notebook looks good, I believe Clancy looked at the rest and approved!

**Pull request merged**
